### ISSUE TITLE
Configuration parameters presentation

### ISSUE THREAD

**Issue by alonbg** [vx3r/wg-gen-web#10]
Configuration is composed of four parts:
1. Server's Interface (the output of `wg showconf wg0` - `Address, ListenPort, keys` )
2. pre/post interface configuration (e.g. `iptables`)
3. global clients peers conf suggested by server (`DNS, MTU, Endpoint, PersistentKeepalive`)
4. per client configuration (`allowedIPs, Address, peer keys`)

I suggest that these 4 parts should be better identified on the UI.
For example
1. first row left column box - "Server's Interface Configuration"
2. first row right column box -  pre/post interface configuration (used by wg-quick)
3. middle row box - "client's global configuration" (`DNS, MTU, Endpoint, PersistentKeepalive` - also used by wg-quick)
4. bottom boxes - client's specific configurations (as it is now).

**Comment by vx3r** [comment]
Done, let me know what you think

**Comment by alonbg** [comment]
I think it looks great. Much clearer. Thank you so much.
