### ISSUE TITLE
Error: 500 - Internal Server Error: 

### ISSUE THREAD

**Issue by duoduo-CCIE** [vx3r/wg-gen-web#103]
Hi !

This is a very good project！This is a very good project. I can't send email right now.

1. logs：

- wg-gen-web   | 2022-04-04T14:56:41.147946940Z time="2022-04-04T14:56:41Z" level=error msg="failed to send email to client" err="534 5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbt\n5.7.14 23hmA_oclTIUbFePKukcRnydT7YNqsd6qSRIb7jw5Q82HhO5obeOgvyl9KxB4UdB-yN7_\n5.7.14 M1lrtLL1IMWdLm7dA6dhgSeYPsfO0tdGUlU2NmY33fMoz-zGVTwjWSZmuuFLqOoM>\n5.7.14 Please log in via your web browser and then try again.\n5.7.14  Learn more at\n5.7.14  https://support.google.com/mail/answer/78754 g5-20020a056a0023c500b004fae15ab86dsm12239530pfc.52 - gsmtp"

- wg-gen-web   | 2022-04-04T14:56:41.148369402Z [GIN] 2022/04/04 - 14:56:41 | 500 |  1.311139946s |  103.172.53.140 | GET      "/api/v1.0/client/eac1702e-4f37-4896-9fda-f186c416d408/email"

- wg-gen-web   | 2022-04-04T14:58:43.603979494Z time="2022-04-04T14:58:43Z" level=error msg="failed to send email to client" err="534 5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbu\n5.7.14 zED9hKRRquRgPGWeSfWSp0cOJdcagMexvGYQbNSZcYWmjUBJajwdXkQJQxO2apfQmYA53\n5.7.14 1DSVPV40au8uaVeMem4mvi1RNLkfO1OnyhMYjeF-VOrvtbUUz86ooLAr4Ks1NGRA>\n5.7.14 Please log in via your web browser and then try again.\n5.7.14  Learn more at\n5.7.14  https://support.google.com/mail/answer/78754 c4-20020a17090a4d0400b001ca5cf3271csm7870237pjg.14 - gsmtp"

- wg-gen-web   | 2022-04-04T14:58:43.604564499Z [GIN] 2022/04/04 - 14:58:43 | 500 |  1.480325319s |  103.172.53.140 | GET      "/api/v1.0/client/eac1702e-4f37-4896-9fda-f186c416d408/email"

2. cocker-compose.yml

version: '3.6'
services:
  wg-gen-web:
    image: vx3r/wg-gen-web:latest
    container_name: wg-gen-web
    restart: always
    expose:
      - "8080/tcp"
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - WG_CONF_DIR=/data
      - WG_INTERFACE_NAME=wg0.conf
      - WG_STATS_API=http://192.168.201.1:8182
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=***@gmail.com
      - SMTP_PASSWORD=***
      - SMTP_FROM=your wireguard info <***@gmail.com>
      - OAUTH2_PROVIDER_NAME=github
      - OAUTH2_PROVIDER=https://github.com
      - OAUTH2_CLIENT_ID=***
      - OAUTH2_CLIENT_SECRET=***
      - OAUTH2_REDIRECT_URL=***
    volumes:
      - /etc/wireguard:/data
  wg-json-api:
    image: james/wg-api:latest
    container_name: wg-json-api
    restart: always
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    command: wg-api --device wg0 --listen 192.168.201.1:8182
networks:
  default:
    name: docker_wg_net1
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.201.0/24"

3. I did proxying and 443 handling using nginx.

**Comment by vx3r** [comment]
Hi,

Thanks for using the app.
The problem is described [here](https://support.google.com/accounts/answer/6010255), not sure if there is a workaround.
You need a working email server that accepts login password auth.
