### ISSUE TITLE
Impossible to disconnect / add / revoke users from the server without restarting it. Statistics on users are also not synchronized without restarting the server

### ISSUE THREAD

**Issue by andrew3203** [vx3r/wg-gen-web#105]
1. It is not possible to add a new user / disconnect a user / remove a user without restarting the server. When adding / deactivating / deleting, only the web interface works, but the apology does not take effect. Those to the disconnected / removed peer can still be connected, but to the newly added peer, on the contrary, cannot be connected. It only helps to restart the server via guard with the command `systemctl restart wg-quick@wg0`

2. User statistics are not synchronized with the user list apology.

**How can this problem be solved?**

**Comment by vx3r** [comment]
It’s clearly explained in readme
