### ISSUE TITLE
Looking for detail installation guide 

### ISSUE THREAD

**Issue by elohffa** [vx3r/wg-gen-web#11]
Hi , could u explain more in details on your pack installation

**Comment by vx3r** [comment]
Hi @elohffa.
Can you please be more precise, which part in readme instructions needs to be detailed ?

**Comment by elohffa** [comment]
when i execute the command : 
sudo docker run --rm -it -v /tmp/wireguard:/data -p 8080:8080 -e "WG_CONF_DIR=/data" vx3r/wg-gen-web:latest
Then I got this error .. 
FATA[0000] failed to migrate                             err="open /data/server.json: no such file or directory"

**Comment by FallingSnow** [comment]
I get the same error.

**Comment by vx3r** [comment]
Hi guys, sorry for this. It has been introduced with the last big changes. 
Should be ok now

**Comment by FallingSnow** [comment]
Seems to be corrected now. Thank you!

**Comment by vx3r** [comment]
@FallingSnow did you manage to run the app with the instructions in readme ? If yes please close the issue, if not let me know that i can help

**Comment by FallingSnow** [comment]
I did.

I did not open the issue so I cannot close.
