### ISSUE TITLE
 ReferenceError: Buffer is not defined 

### ISSUE THREAD

**Issue by gudata** [vx3r/wg-gen-web#115]
When I run with the docker I always get this error in the UI.

Digest: sha256:fb40ad10bb78b12a940366530ebc485a3750aad20f2587b2b6ea9f4c1cfa4312
Status: Downloaded newer image for vx3r/wg-gen-web:latest

**Comment by phill22** [comment]
same here

**Comment by gianni4711** [comment]
same here

**Comment by phill22** [comment]
it's in the main page if it would like generated QR codes. qr codes didn't load.

**Comment by vx3r** [comment]
resolved
