### ISSUE TITLE
Wanna work together and add this to my installer?

### ISSUE THREAD

**Issue by Prajwal-Koirala** [vx3r/wg-gen-web#12]
Hey I have a wireguard installer with over 2500 clones and 300 stars and I think this would be an amazing side thing to add to that so instead of a CLI only users would be able to use a GUI too.

What do you think about it??

**Comment by vx3r** [comment]
Hey @Prajwal-Koirala I think it would be nice yeah! Can you share the repository I can take a look ? 
Thx

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-installer-manager

Right now it's entirely CLI but I feel like if we will have normal people using it too, instead of just developers and programmers.

**Comment by vx3r** [comment]
Thank you. In `Wg-Gen-Web` you basically have all features listed in `wireguard-installer-manager`. How do you want to merge both project ? What is the added value of `wireguard-installer-manager` ?

**Comment by Prajwal-Koirala** [comment]
I am not sure, I am in bed right now and can't really read the code.

I have a quick question, why don't you build this in material design??

99% of the people who aren't devs don't really care about code they just care about how it looks and if this looks nice and pretty we can attract normal people to this project.

**Comment by vx3r** [comment]
I should put all frameworks used in project in readme...
Frontend is based on [Vuetify ](https://vuetifyjs.com/en/) which is a Vue UI Library with beautifully handcrafted Material Components. Try to run a docker and let me know what we can do better, always open to add features

**Comment by Prajwal-Koirala** [comment]
> I should put all frameworks used in project in readme...
> Frontend is based on [Vuetify ](https://vuetifyjs.com/en/) which is a Vue UI Library with beautifully handcrafted Material Components. Try to run a docker and let me know what we can do better, always open to add features

Do you have discord or something??

**Comment by vx3r** [comment]
Sure, everyone is welcome to join [discord ](https://discord.gg/fjx7gGJ)channel

**Comment by Prajwal-Koirala** [comment]
I tried to join the channel coudent join.

**Comment by vx3r** [comment]
What is the problem ? @N0jja can you please confirm that the link works for you ?

**Comment by N0jja** [comment]
@Prajwal-Koirala @vx3r All good for me, joined earlier today for the first time.
Invite link is set to infinite use so, as long as you are connected with your account on discord, it should work.
What issue are you facing exactly ?

**Comment by zmingxie** [comment]
Have you guys checked out Algo? https://github.com/trailofbits/algo

It seem to me trying to set up wireguard with a shell script that supports multiple platforms is a bit difficult to maintain.

**Comment by Prajwal-Koirala** [comment]
> Have you guys checked out Algo? https://github.com/trailofbits/algo
> 
> It seem to me trying to set up wireguard with a shell script that supports multiple platforms is a bit difficult to maintain.

its too complicated for a vpn setup, it should be as simple as possible.
