### ISSUE TITLE
Error failed to launch wire-guard in LXC Proxmox Server

### ISSUE THREAD

**Issue by hakatu** [vx3r/wg-gen-web#121]
My docker launch stucks at

`root@WireguardWeb:~# docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
root@WireguardWeb:~# docker run --rm -it -v /tmp/wireguard:/data -p 8080:8080 -e "WG_CONF_DIR=/data" vx3r/wg-gen-web:latest
Unable to find image 'vx3r/wg-gen-web:latest' locally
latest: Pulling from vx3r/wg-gen-web
8921db27df28: Pull complete 
c681266e7edc: Pull complete 
ad4ce1801140: Pull complete 
bf4810938c17: Pull complete 
270535afe83d: Pull complete 
4f4fb700ef54: Pull complete 
11f47600467e: Pull complete 
Digest: sha256:868023ba4c07f3c3b638b32617cd897dcad1dae8cbac9de437ec6d9618d6db45
Status: Downloaded newer image for vx3r/wg-gen-web:latest
INFO[0000] Starting Wg Gen Web version: 4fd1e34         
WARN[0000] Oauth is set to fake, no actual authentication will be performed `

after:

`docker run --rm -it -v /tmp/wireguard:/data -p 8080:8080 -e "WG_CONF_DIR=/data" vx3r/wg-gen-web:latest`

LXC running

`Linux 5.15.102-1-pve #1 SMP PVE 5.15.102-1 (2023-03-14T13:48Z) x86_64`

**Comment by Gunking98700** [comment]
How did you fix this problem?
