### ISSUE TITLE
[QUESTION} Is this project still being maintained?

### ISSUE THREAD

**Issue by bmcgonag** [vx3r/wg-gen-web#126]
First and foremost, thank you for making this an open source project. 

Just found this project. Looks like a nice in between for those wanting more than Wg-Easy, but not quite so complex as Tailscale / Headscale or Netbird. 

Just curious before I try it out.

**Comment by vx3r** [comment]
Hi @bmcgonag the app works, i still use it. However, i have way less time to maintain it unfortunately

**Comment by bmcgonag** [comment]
Good to know, and I understand completely.  Closing as answered.
