### ISSUE TITLE
Mobile version and fixed size artefacts

### ISSUE THREAD

**Issue by wsw70** [vx3r/wg-gen-web#14]
I am not sure this is fixable, and whether it should be but FYI the mobile version of the site is somehow impacted by some fixed-size artefacts:

![image](https://user-images.githubusercontent.com/1345886/75022406-540a2500-5496-11ea-95e8-0c65a5d3d078.png)

This is not a show stopper as all the information is there (though, maybe there are issues with editing the IP ranges as the cross is eaten by the badge) - I am raising the point just in case there would be some more mobile dev.

The web version is truly fantastic, thanks for that.

**Comment by vx3r** [comment]
Thank you for rising this point, im aware of the issue but i need some time to dig deer in Vuetify to make the web page fully responsive. If someone is more familiar with the framework PRs are welcome
