### ISSUE TITLE
SMTP sender configuration issue (SMTP_FROM)

### ISSUE THREAD

**Issue by wsw70** [vx3r/wg-gen-web#15]
The example for the SMTP configuration is

      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=account@gmail.com
      - SMTP_PASSWORD="*************"
      - SMTP_FROM="Wg Gen Web <account@gmail.com>"

With this setup (and of course actual, correct data) I get the following error

    time="2020-02-21T10:41:56Z" level=error msg="failed to send email to client" err="gomail: could not send email 1: gomail: invalid address \"\\\"Wg Gen Web <account@gmail.com>>\\\"\": mail: no angle-addr"

Changing `SMTP_FROM` to

    - SMTP_FROM=Wg Gen Web <account@gmail.com>

 (→ no quotes) fixes the problem and emails are sent out correctly.

**Comment by vx3r** [comment]
[Docker env and quotes](https://github.com/moby/moby/issues/36027) haha, thank you
