### ISSUE TITLE
Format server.json file

### ISSUE THREAD

**Issue by wsw70** [vx3r/wg-gen-web#2]
First of all - thank you very much for this great interface to WireGuard. It makes the management of configurations so much easier.

It would be worthwhile I believe to have `server.json` pretty-printed, instead of the raw version today → it would make it way easier to edit if needed.

```
{
    "name": "Created with default values",
    "created": "2020-01-31T15:05:13.522502946Z",
    "updated": "2020-01-31T15:07:03.521605467Z",
    "address": "fd9f:6666::10:6:6:1/112, 10.6.6.1/24",
    "listenPort": 51820,
    "privateKey": "gM...=",
    "publicKey": "C4...=",
    "presharedKey": "9wzD/gZHeTD2Bkco2wYWXq21pZJHMSweuUbzFSFNv4I=",
    "endpoint": "wireguard.example.com:123",
    "persistentKeepalive": 16,
    "dns": "fd9f::10:0:0:2, 10.0.0.2"
}
```

Thanks again for sharing wg-gen-web.

**Comment by vx3r** [comment]
I'm glad you find it useful. 
True, it will be much more easier to put existing keys.
Done
