### ISSUE TITLE
Per client preshared key

### ISSUE THREAD

**Issue by andofrjando** [vx3r/wg-gen-web#23]
Firstly, thanks for creating such a neat UI to manage WireGuard configs - this makes like so much easier!

I noticed that the generated client configs all use the same pre shared key. Given that the pre shared key is configured in each `[Peer]` section, would it be at all possible to have a separate pre shared key for each client? Essentially moving the pre shared key into each clients JSON file instead of storing a single one in the server's json file? It needn't be exposed in the UI.

**Comment by vx3r** [comment]
Thank you @andofrjando for using Wg Gen Web. 
This design is coming from my misunderstanding of preshared key usage. 
You are completely right, given the automation of all configurations it’s better to have a preshared key for each client.
It will be implemented! Thank you again for the point
