### ISSUE TITLE
Migrate from Subspace

### ISSUE THREAD

**Issue by deprito** [vx3r/wg-gen-web#24]
Any tips from us, when migrating from subspace to wg-gen-web?
I'm very interested...

**Comment by vx3r** [comment]
You want to keep your subspace clients or server configuration?

**Comment by deprito** [comment]
Yes @vx3r ! I have existing clients/server configuration.. I want to migrate all vpn data that exists on subspace, to wg-gen-web...

**Comment by vx3r** [comment]
can you provide a client config example ?

**Comment by deprito** [comment]
Attached sample from subspace


{
    "info": {
        "email": "registereduseremail",
        "password": "ourpassword",
        "secret": "oursecretkey",
        "configure": true,
        "domain": "",
        "hash_key": "ourhashkey",
        "block_key": "ourblock_key",
        "saml": {
            "idp_metadata": "",
            "private_key": "ourprivatekeyssl
            "certificate": "ourssl
        },
        "mail": {
            "from": "",
            "server": "",
            "port": 0,
            "username": "",
            "password": ""
        }
    },
    "profiles": [
        {
            "id": "clientID",
            "user": "",
            "name": "clientID-Name",
            "platform": "osx/android/unknown",
            "number": 2 ,
            "created": "2019-09-25T15:52:53.665909642+07:00"
        },
        {

**Comment by vx3r** [comment]
where are the server and client private / public keys ?

**Comment by deprito** [comment]
> where are the server and client private / public keys ?

for wireguard client configuration, located in /data/wireguard (Docker pointing volume in /data)
Separated with folder wireguard/clients & wireguard/peers

For server wide private & public, located in /data/wireguard/server.private | /data/wireguard/server.public also server.conf

**Comment by vx3r** [comment]
i need an example of all these files to make the import function, basically read all subspace files and "translate" them into wg-gen-web config files

**Comment by deprito** [comment]
Any email for send the attachment?

**Comment by vx3r** [comment]
sure: vx3r@127-0-0-1.fr

**Comment by deprito** [comment]
> sure: [vx3r@127-0-0-1.fr](mailto:vx3r@127-0-0-1.fr)

Sent, thankyou!

**Comment by vx3r** [comment]
thank you @deprito 

If  you run the script `python3 subspace_to_wg-gen-web.py -in data -out out` it will give you the directory layout above
```
.
├── data
│   ├── config.json
│   ├── letsencrypt
│   │   ├── acme_account+key
│   │   └── kilat.deprito.net
│   └── wireguard
│       ├── clients
│       │   ├── 0M-fGf0I5QzRW7yG.conf
│       │   ├── ma93I7iAS7p6I4pu.conf
│       │   └── QYcR0MsCnSkSScAS.conf
│       ├── peers
│       │   ├── 0M-fGf0I5QzRW7yG.conf
│       │   ├── ma93I7iAS7p6I4pu.conf
│       │   └── QYcR0MsCnSkSScAS.conf
│       ├── server.conf
│       ├── server.private
│       └── server.public
├── out
│   ├── 4d0771f1-085a-486d-94d7-d56a6d79af1f
│   ├── 6b9d0bf1-3996-469d-af08-b067c9bd493a
│   ├── 92ca3ba8-ece6-4be2-8e30-b0ff1cb73d62
│   └── server.json
└── subspace_to_wg-gen-web.py
```
`out` directory can be used as input to Wg Gen Web.

Some remarks:
- what a mess, subspace config directory is a mix of `json` end `ini` files
- `presharedKey` is not used at all 
- i didnt tested if the output works with existing client without `presharedKey`

I strongly recommend regenerating the clients with Wg Gen Web.
I will implement issue #23 soon to correct `presharedKey` usage. 

The python script attached.
[subspace_to_wg-gen-web.zip](https://github.com/vx3r/wg-gen-web/files/4342506/subspace_to_wg-gen-web.zip)

Im sorry but i will not implement the import in Wg Gen Web Go binary. I hop you can import your clients using this script.

**Comment by deprito** [comment]
Thank you, i have success migrate our client... Thank You a lot!
