### ISSUE TITLE
TLS support for sending email

### ISSUE THREAD

**Issue by ronyshtamler** [vx3r/wg-gen-web#25]
Please add TLS support for SMTP, as most services mandate TLS connection.

d.TLSConfig = &tls.Config{InsecureSkipVerify: true} 
(or use env for setup)

Thanks,

**Comment by vx3r** [comment]
The usage of TLS depends which SMTP port you specify:
- 25: SMTP without TLS
- 465: SMTPS with TLS
- 587: SMTP with STARTTLS

in `gomail` `Dialer` struct 
```
	// SSL defines whether an SSL connection is used. It should be false in
	// most cases since the authentication mechanism should use the STARTTLS
	// extension instead.
	SSL bool
	// TSLConfig represents the TLS configuration used for the TLS (when the
	// STARTTLS extension is used) or SSL connection.
	TLSConfig *tls.Config
```
In example SMTP config with gmail STARTTLS will be used.

Your suggestion `d.TLSConfig = &tls.Config{InsecureSkipVerify: true}` is highly unsecure! Please avoid posting this kind of information without any security warning. 

If its still not clear please provide error logs and your SMTP configs for further investigation

**Comment by ronyshtamler** [comment]
> Your suggestion d.TLSConfig = &tls.Config{InsecureSkipVerify: true} is highly unsecure! Please avoid posting this kind of information without any security warning.

You are right!. I was so convinced that the problem is the TLS, that I didnt think about that. 

My problem:
wg-gen-web    | time="2020-03-17T08:14:07Z" level=error msg="failed to send email to client" err="dial tcp: i/o timeout"

I setup all the env variables and rechecked that they are set using docker inspect.

**Comment by vx3r** [comment]
As pointed by the error message is a timeout issue. Please verify that your docker container can access email server. For example using `netcat` with something line  `nc smtp.example.com 587`. You must install the tool in your docker with `apk add netcat`.
Or share your server IP and port i can check for you, if the server is publicly accessible

**Comment by vx3r** [comment]
please reopen if you still can not send email

**Comment by ronyshtamler** [comment]
Just for documentation:
My problem was with the IPTABLES rules on the docker container. Once I allowed outbound traffic, Everything was OK.

Thank you

**Comment by vx3r** [comment]
As mentioned in readme Wg Gen Weg is not touching (iptables, nft, service or whatever) your host system at all. It’s your responsibility to ensure WireGuard and underlying system is fully configured and working before use this tool to automate client config generation. 
Glad you figured out the issue.
