### ISSUE TITLE
Suggestion , CLIENTS UI as Tabular list.

### ISSUE THREAD

**Issue by aniston** [vx3r/wg-gen-web#27]
Hello,
I like your idea and project, thanks for the good work.

A suggestion towards the CLIENTS UI, i think it would be more useful to have the CLIENTS TAB as a Tabular list rather than each CLIENT being shown in Card form with the QR codealongside.

This is because the CLIENT and SERVER Tabs would normally be administered by an administrator not by the actual Client user. This way realestate screenspace can be better utilized , also not being the actual user there is no direct need for the QR code upfront on screen, a link should suffice (or a mouseover event).

just a thought, sadly i'm not a programmer to help out.

as said before good work ;)

Best Regards,
Aniston

**Comment by vx3r** [comment]
Hi @aniston 
Thank you for using my app. 
I personally like cards but I can add a client tab as well, you will be able to switch the view. 
Let me a couple of days to add this  (:

**Comment by aniston** [comment]
wow, thanks for the quick response.
will test and give feedback when you have implented something.

**Comment by jrester** [comment]
I also prefer the card view but for a large amount of clients the view gets quite confusing. A list would improve this a lot and you can much easier take a look at all clients.

But if there is support for multiple users maybe a hybrid approach would work better. So that every user has a card view of the different devices that belong to him and an administrator view which is a list of all the users and their devices.

What do you think?

**Comment by aniston** [comment]
@jrester , from my point of view the administrator looking at a table of clients is fully justified, the card view looks neat, but often drilling down and finding IP's, Names or emails etc. etc.  (for whatever reasons) is what an Administrator would do apart from just adding , removing or configuring clients.

I had mentioned that the Clients QR code would not be much to an Admin as that is something he would not use to actually administer the users, but that is my use perception , but must say looking at a QR code alongside a name is undoubtly shiny and gives the panel a morden day approach.

Lastly, the importance of a highlighted line (if possible in the UI) will make the use case very important to drilling down thru many users details.

Sadly as said in my first post, I am zero with GO and GIN and I still do not know even the skeletal approach to the whole environment used in the Docker Container, but that is my deficiency, although willing to learn with some useful pointers ;)

**Comment by vx3r** [comment]
i agree that admin view with a table of clients is better,but i dont really work on multi user implementation right now.  I still dont know what do we need for a multi user part?
- Authelia forward user and group in http headers 
- Wg Gen Web for admin
1. server configs
2. table of clients 
- Wg Gen Web for user
1. card view of user devices 
And last part, add and edit allowed only on admin side.
Dose this make sens ?
Also do you think that Authelia usage will impact users ? My initial goal was to make it really easy and not force people to use anything (iptables, nftables or whatewer) for the config generation. 
Maybe i need to let the choice with or without Authelia (multi user or not ).
Thank you all for your feedback

**Comment by jrester** [comment]
@aniston I totally agree with you!
> Sadly as said in my first post, I am zero with GO and GIN and I still do not know even the skeletal approach to the whole environment used in the Docker Container, but that is my deficiency, although willing to learn with some useful pointers ;)
I added development instructions to the README. Hope that helps you to get started!

@vx3r I also don't like the idea of being forced to use an extra service like authelia especially because not everybody needs multiple users and access right management. Do you think it might be better to directly include the authentication part into the app? Through something like [casbin](https://github.com/casbin/casbin) or some simple self-made implementation. I have never worked with it but it looks promising. What do you think?

But maybe a first step would be the logical separation of clients into devices which can be associated with different users. Because often you have multiple clients for different devices that all belong to one user. In a later step access right management and multiple user support could be implemented.

**Comment by aniston** [comment]
@jrester Thanks for the starter tips in the README.md, got the Backend and Frontend running, but this is outside the docker container on a Windows machine, is there anyway to modify the running docker container as a development machine , that I can save back as a new docker image. Not sure if that makes sense, but for now atleast I have something rolling to play with :+1: 

@vx3r , in the README.md there is a small mixup in the download links under "Directly without docker", ie: Backend downloads the frontend files and vice versa :) sendng a PR to correct, please check if that is correct.

As for the discussion on Authelia, I have not used it as yet, what I understand from linking Authelia with wg-gen-web depends on the many use cases, which can differ completely, for eg:

- in a multi App scenario where the WG client user probably need a SSO (SingleSignOn) to go from one App to another then this can be useful, but still I do not see how that could benifit from and Administrator point of view. I don't know if you mean to let the Client directly loginto the web interface?
- in a pure VPN link structure (my case) the client has nothing to do with SSO or Authelia , Client is happy to just get to the other side of the Tunnel (WG in this case) there is no more use of the AUTH Token or SSO Object once the VPN is up as there are no Apps involved within and beyond the scope of the tunnel, just networking resources. In my case I'm trying to use wg-gen-web to add, edit, activate, and keep track of Clients configurations and IP's basically Administration, but in no way is the Client getting to see the web interface , when required he gets the config via e-mail or messenger services.

I see a good use as an Administration tool, here I wonder if an Admin will let Clients/Users generate their own configs, wich will eventually be a mess between the network topology! At best admins like to send the client configuration via e-mail to the client. I do not think the goal should be multi client but multi Admin would definately help, but then logging will be needed to see which Admin made what changes and where, this I feel is not required at the moment, as it just complicates the usefulness currently.

All said it's good to know scenarios from other use cases to get a broader picture.

**Comment by jrester** [comment]
@aniston So you are running the development server inside the docker container? It is possible to commit the container and save it to an image but normally you want to build the image using the Dockerfile because you later want to publish the changes as source code not as a container.

Have you tried using WSL? That way you can modify the code in VSCode and run the dev server inside WSL without the use of docker. 

I saw the use of multi user in a scenario where you have multiple users each of them having their own devices and you as the administrator don't want to cope with the management of all the different devices each user has. So I would just give a user the permission to create and delete clients so they can handle everything themselves. Not sure if that makes sense or I put too much trust into my clients :)

But I still believe the logical division of clients into users and devices would be beneficial. @vx3r is it fine with you if I take a shot at this. Without all the client accessing the web interface stuff just for the admin.

**Comment by vx3r** [comment]
> @aniston I totally agree with you!
> 
> > Sadly as said in my first post, I am zero with GO and GIN and I still do not know even the skeletal approach to the whole environment used in the Docker Container, but that is my deficiency, although willing to learn with some useful pointers ;)
> > I added development instructions to the README. Hope that helps you to get started!
> 
> @vx3r I also don't like the idea of being forced to use an extra service like authelia especially because not everybody needs multiple users and access right management. Do you think it might be better to directly include the authentication part into the app? Through something like [casbin](https://github.com/casbin/casbin) or some simple self-made implementation. I have never worked with it but it looks promising. What do you think?
> 
> But maybe a first step would be the logical separation of clients into devices which can be associated with different users. Because often you have multiple clients for different devices that all belong to one user. In a later step access right management and multiple user support could be implemented.

Sorry for the late reply, I was quit busy.
I don’t really want to implement a user management into the application, I thought authelia can be a quick win, they also have double authentification which I personally use a lot. 
Regarding the separation between users and devices I agree that we need to implement that first.

**Comment by vx3r** [comment]
> @jrester Thanks for the starter tips in the README.md, got the Backend and Frontend running, but this is outside the docker container on a Windows machine, is there anyway to modify the running docker container as a development machine , that I can save back as a new docker image. Not sure if that makes sense, but for now atleast I have something rolling to play with 👍
> 
> @vx3r , in the README.md there is a small mixup in the download links under "Directly without docker", ie: Backend downloads the frontend files and vice versa :) sendng a PR to correct, please check if that is correct.
> 
> As for the discussion on Authelia, I have not used it as yet, what I understand from linking Authelia with wg-gen-web depends on the many use cases, which can differ completely, for eg:
> 
> * in a multi App scenario where the WG client user probably need a SSO (SingleSignOn) to go from one App to another then this can be useful, but still I do not see how that could benifit from and Administrator point of view. I don't know if you mean to let the Client directly loginto the web interface?
> * in a pure VPN link structure (my case) the client has nothing to do with SSO or Authelia , Client is happy to just get to the other side of the Tunnel (WG in this case) there is no more use of the AUTH Token or SSO Object once the VPN is up as there are no Apps involved within and beyond the scope of the tunnel, just networking resources. In my case I'm trying to use wg-gen-web to add, edit, activate, and keep track of Clients configurations and IP's basically Administration, but in no way is the Client getting to see the web interface , when required he gets the config via e-mail or messenger services.
> 
> I see a good use as an Administration tool, here I wonder if an Admin will let Clients/Users generate their own configs, wich will eventually be a mess between the network topology! At best admins like to send the client configuration via e-mail to the client. I do not think the goal should be multi client but multi Admin would definately help, but then logging will be needed to see which Admin made what changes and where, this I feel is not required at the moment, as it just complicates the usefulness currently.
> 
> All said it's good to know scenarios from other use cases to get a broader picture.

I was actually thinking of letting clients generate N devices but you are right it can be a mess with the ip addresses (I use 3 ranges to go out in different locations). 

We must decide if a user can have access to the web portal (to just see devices infos) or only admins will have access to manage everything.

**Comment by aniston** [comment]
@vx3r 
> We must decide if a user can have access to the web portal (to just see devices infos) or only admins will have access to manage everything.

- I'd vote for only admins to have access to the web portal and manage things or sort out customer config. As an example, we are using many VPN clients with our customers and we (as a client side approach connecting to their servers) are and never allowed to their VPN management systems, if the VPN fails or has problems then the Administrator or Customer manager is our e-mail or telephone contact point  and the isse would be resolved, this goes for all our customers VPN servers right from Ctrix, Sophos, Cisco, OpenVPN, IPSEC and some other players too.
- Currently I'm  implementing our own WG VPN to a small customer and find it useful not to have the customer directly see the web portal and only send his client config via e-mail. This is good and safer without the added bloat of client logon infrastructure and security and to avoid more logons and more password management parallel to the acutual VPN usage.

**Comment by aniston** [comment]
@jrester 
> @aniston So you are running the development server inside the docker container? It is possible to commit the container and save it to an image but normally you want to build the image using the Dockerfile because you later want to publish the changes as source code not as a container.
- yes that is my case, and I see what you mean of publishing the source code changes, had a mix up of ideas there.

> Have you tried using WSL? That way you can modify the code in VSCode and run the dev server inside WSL without the use of docker.
- no never used WSL, but at the moment I still have to get my head around the GO lang and GIN Framework, which for me will take a long time. Thanks for the tips though, I sure was able to get started atleast :)

I think I will cut short the dev threads here as they are going off topic to the original issue for the fairness of anyone trying to follow the Issue.

**Comment by vx3r** [comment]
Ok i will implement oauth2 and authelia, I personally use authelia so I need it. 
Only admin will be able to connect to the interface and create clients.

**Comment by vx3r** [comment]
OAuth2 OIDC is implemented, for any issue please reopen
