### ISSUE TITLE
wg0.conf not updating

### ISSUE THREAD

**Issue by sebstrgg** [vx3r/wg-gen-web#35]
Hi,

Great project - really like the flexibility of the UI which I haven't seen in any other gui's for wireguard yet. Super easy and the e-mail function works great!

I did discover something that may be due to how I setup my docker container, where the wg0.conf isn't updated but instead a wg0 file is being generated alongside. 

In other words it seems like I need to the following to get new clients up and running:

```
mv wg0 wg0.conf
wg-quick down wg0; wg-quick up wg0

```
My questions is really if this is expected or if I should have done something else with the setup?

**Comment by sphen13** [comment]
@sebstrgg care to share your docker-compose or docker run command (sanitized of course)?

**Comment by vx3r** [comment]
@sebstrgg thank you! 
Please as suggested share your setup that we can help, the behavior you are observing is not expected.
Also look at the WG_INTERFACE_NAME config in .env file if you are running directly the binary

**Comment by sebstrgg** [comment]
Wow, such a quick response @sphen13 & @vx3r . Unfortunately I wasn't as fast :)

This is my docker run command:

docker run -d --name wg-web --restart always --privileged --cap-add=all -p 8080:8080 -e "WG_CONF_DIR=/data" -e "WG_INTERFACE_NAME=wg0" -v "/etc/wireguard:/data" -e "SMTP_HOST=smtp.example.com" -e "SMTP_PORT=587" -e "SMTP_USERNAME=x@x.se" -e "SMTP_PASSWORD=x" -e "SMTP_FROM=x@x.se" vx3r/wg-gen-web:latest

I can see now that I should probably just have entered "wg0.conf" for the interface env, right?

Can I expect that the interface are refreshed automatically upon config changes?

**Comment by sebstrgg** [comment]
I can confirm that by changing WG_INTERFACE_NAME to "wg0.conf" that the actual file was changed properly. Although it still seems like I need to do wg-quick down and up to get a handshake with the server.

**Comment by vx3r** [comment]
As detailed in readme Wg Gen Web will not restart WireGuard, there are multiple ways to automate the restart. Please check readme if needed

**Comment by sebstrgg** [comment]
You are perfectly right, the problem was that I didn't realize the wg-gen-web.service couldn't be started as the path for systemctl was incorrect (/usr/bin/systemctl -> /bin/systemctl for Ubuntu 18.04 LTS).

**Comment by vx3r** [comment]
yep `/usr/bin/systemctl` is for ArchLinux
