### ISSUE TITLE
Allow choice between using pre-shared key or not

### ISSUE THREAD

**Issue by sphen13** [vx3r/wg-gen-web#36]
might be good to allow a default server setting on whether we used pre-shared keys and then also a setting on an individual client basis.

**Comment by vx3r** [comment]
What is the point of not using the preshared key ? 
If there is a real impact we can consider adding the option.

**Comment by sphen13** [comment]
in looking into it it seems there is some debate on whether this extra layer of encryption adds overhead and slows the connection. some people prefer not to use preshared keys while others do. i could whip up the change - probably as easy as the last one i made was :)

**Comment by vx3r** [comment]
The symmetric encryption (preshared key) is always much much more fast that asymmetric encryption (public and private keys). Now that said if someone can show me that the impact is significant im ok to accept the PR. Meanwhile as a security engineer i prefer to keep preshared key

**Comment by sphen13** [comment]
after reviewing further i would have to agree with you. I am not a security engineer either so would defer to you :)

looking at the docs it appears that even if you dont specify a pre-shared key it still does that extra symmetric encryption layer, just with a zeroed out key. so i would imagine there is zero impact difference between specifying one and not.

thx!
