### ISSUE TITLE
Force Default Allowed IPs for client

### ISSUE THREAD

**Issue by yoohahn** [vx3r/wg-gen-web#37]
His. Love this project!
But have a small request. Is it possible to have a checkbox or something similar to force the `Default Allowed IPs for client` to be applied to already existing peers?

Today the peers Allowed IPs is based the list of ips that exists during it's creation time. Would be nice to just add in the server part and all peers to be updated with this new setting.

**Comment by vx3r** [comment]
hi @yoohahn 
Im working on a authentication with OAuth2, will add this after

**Comment by vx3r** [comment]
done, please reopen if needed
