### ISSUE TITLE
Pagination + Search

### ISSUE THREAD

**Issue by deprito** [vx3r/wg-gen-web#38]
Is it possible for dashboard using pagination + search? so admin can easily search vpn configuration.

Because for now, to load 500+ users configuration, it takes around 8-10s.. After scrolling, it will glitch and takes another 5s or more...

Thank you!

**Comment by vx3r** [comment]
i will add a table view (issue #27) after SSO implementation. 
Hopefully this weekend

**Comment by deprito** [comment]
> i will add a table view (issue #27) after SSO implementation.
> Hopefully this weekend

Thank you! Take your time @vx3r ! Keep safe, stay healthy!

**Comment by vx3r** [comment]
please reopen if needed
