### ISSUE TITLE
I can not create a user with the latest version (f90124a)

### ISSUE THREAD

**Issue by nestyurkin** [vx3r/wg-gen-web#39]
Latest docker release - Version: f90124a
I can not create a user  in UI, Submit button is not pressed

downgraded to Version: 867d79e  - fix problem
several servers are affected

**Comment by vx3r** [comment]
Can you please test on demo server ? I just tried and it works, please check your server setting. You can compare with the demo

**Comment by nestyurkin** [comment]
thank! found
if **Default Allowed IPs for client** empty - i cant save new user

**Comment by vx3r** [comment]
Make sens
