### ISSUE TITLE
PostUp, PostDown options

### ISSUE THREAD

**Issue by alex-phillips** [vx3r/wg-gen-web#4]
Would be nice to have an added textarea for additional server config options. Or expose PostUp and PostDown as optional fields for the server configuration.

**Comment by vx3r** [comment]
Hi @alex-phillips,

Thank you for your suggestion. [Added](https://github.com/vx3r/wg-gen-web/commit/26dec5ce7ab1eb763685fb51280d527b5b6cdcc5)

**Comment by alex-phillips** [comment]
Nice, thanks!
