### ISSUE TITLE
Simple page refresh updates wg0.conf

### ISSUE THREAD

**Issue by alexandergolz** [vx3r/wg-gen-web#47]
Hi, I installed this service successfully and configured systemd to monitor /etc/wireguard to reload wireguard configuration as per your instructions in the Readme. But it seems that on every simple GET of the web ui, without changing any setting wg0.conf gets updated and therefore wireguard restarted. Is this the expected behavior? Isn't this a problem because of service interruption? Thanks for this nice gui!

**Comment by nikosch86** [comment]
I am using the UI in production and can not reproduce this behavior, same setup, systemd with a path and service unit to monitor and trigger restart.
Would you have more details?

**Comment by vx3r** [comment]
Hello, indeed its a bug. 
Just pushed correction.

Thank you for reporting

**Comment by alexandergolz** [comment]
Thanks, it seems to work now!

**Comment by Girgitt** [comment]
How nice. 
For anyone running an older version a possible workaround for this issue is to compare md5 checksums of a working config file and the output config file e.g. with a script (assuming md5sum is available): 

```
# cat /opt/wg-gen-web/restart_wg_on_config_change.sh

#!/bin/sh

while inotifywait -e close_write /opt/wg_working_dir/wg0.conf; do
  file1=`md5sum /etc/wireguard/wg0.conf | cut -d " " -f1`
  file2=`md5sum /opt/wg_working_dir/wg0.conf | cut -d " " -f1`
  if [ "$file1" = "$file2" ]
    then
      echo "wg0 config didn't change"
    else
      echo "wg0 updated"
      cp -f /opt/wg_working_dir/wg0.conf /etc/wireguard/wg0.conf
      wg-quick down wg0
      wg-quick up wg0
  fi
done
```
