### ISSUE TITLE
DNS setting is not saved

### ISSUE THREAD

**Issue by simulot** [vx3r/wg-gen-web#48]
Hi,
Thank for this project. Simple, efficient, easy to run on my nas in a docker compose stack.

Anyway, I have a small issue:
I can't give a DNS on server configuration. wg0.conf is updated, with a timestamp. But DNS field is still missing

++ Simulot

**Comment by vx3r** [comment]
Hi, thank you for using Wg Gen Web.

DNS settings are for clients, there is no DNS option on server side. Please read Wireguard documentation for more info.
If you have an issue with generated config fill free to describe in details

thank you

**Comment by simulot** [comment]
Hi, 
I have rebuild the setup using CLI... and now it's working.  So, I'd prefer not touching it.

So I can't elaborate this. 
Thanks for your help.
