### ISSUE TITLE
protect page

### ISSUE THREAD

**Issue by raldridgenctm** [vx3r/wg-gen-web#6]
I understand you're working to implement Authelia, but is there any simple way now to protect the page with even a simple password?

**Comment by vx3r** [comment]
@raldridgenctm you can always put an nginx revers proxy with basic auth in front of wg-gen-web. I’m not really working on Authelia yet, I need some inputs to understand if the implementation will be useful or not.

**Comment by pomazanbohdan** [comment]
All revers proxy (caddy/traefik) support basic authentication to any site

**Comment by raldridgenctm** [comment]
Sorry for the noob question, but to restrict access to the local site, would that just be done by a firewall rule and restricting access to only the IP of the reverse proxy server?

**Comment by vx3r** [comment]
@raldridgenctm i believe the question is more about authentication for public access.
You are partially right for local access.
