### ISSUE TITLE
Add posibility to have it in a subpath

### ISSUE THREAD

**Issue by kammerjaeger** [vx3r/wg-gen-web#7]
It would be nice to configure that the files are served in a subpath by the reverseproxy.
I want to use traefik as a reverse proxy (with authentication) and not define another host dns name for the ui.
Example:
http://a.b.com/wggen/...

**Comment by vx3r** [comment]
I dont really like the idea of service each app based on prefix. I need to configure both backend and frontend, backend to pick dynamic prefix and frontend to add prefx in generated static files.. 
What is the issue of adding a dedicated CNAME or wildcard domain entry ?

**Comment by kammerjaeger** [comment]
If it is too much work, I can add another cname. I just have already a lot of them (15 or so). Wildcard was my next idea so I may go that route next. I maybe hoped to get around the dns server reconfiguration for inside and outside dns requests.
I did not look at your code, I just thought that relative paths between the links or something like that could work. Also I could then probably use the traefik stripprefix middleware to remove the path before it goes to the app.

In general, people that have to work with one dns name would have to use a different port to make the app working. In my case I have Strict-Transport-Security enabled so at the moment I'm accessing it by ip.

**Comment by wsw70** [comment]
@kammerjaeger 
> Wildcard was my next idea so I may go that route next

This is what I use (on `dnsmasq`) to handle the farm of my docker containers and route them via traefik. It really simplified the configuration long term in my case.
