### ISSUE TITLE
How to start the API?

### ISSUE THREAD

**Issue by wsw70** [vx3r/wg-gen-web#76]
> Wg Gen Web integrates a WireGuard API implementation to display client stats. In order to enable the Status API integration

It looks like, however, that `8182` is not bound to:

```
~ ➤ lsof -i -P | grep 8182
~ ➤
```

Is there something special to do to start the API?

**Comment by sukram230799** [comment]
Did you use the docker-compose or the docker command?? The `wg-json-api` available under `8182` is not a part of the docker container but is a separate container that can be added (most easily through using the provided docker-compose).

**Comment by wsw70** [comment]
> most easily through using the provided docker-compose

Well, this is how you end up asking such a dumb question after having used `wg-gen-web ` from the start and not having realized that the `docker-compose.yaml` has changed :)

Thanks a lot - I completely missed the fact that there was a new, separate component.
