### ISSUE TITLE
crashes due to multiple CIDRs input

### ISSUE THREAD

**Issue by alonbg** [vx3r/wg-gen-web#8]
how to reproduce from the UI

```
In the "Server interface addresses field type:
fd42:42:42::1/64
<enter>
10.8.0.1/24
<enter>
click "update server configuration"
```

a stack trace starting with `fatal error: runtime: out of memory` is dumped

with only a single ipv4 CIDR  there is no problem

**Comment by vx3r** [comment]
hi @alonbg. Im aware of this limitation, basically its because im generating a list of all IP addresses from given cidr before picking an available IP address. For an IPv6 /64 cidr it makes a huge list... I will correct it tomorrow, Tokyo time.
Thank you

**Comment by vx3r** [comment]
[pushed ](https://github.com/vx3r/wg-gen-web/commit/6cafb97e311e5e91f6c9bbee690a2c452841de7d)
