### ISSUE TITLE
Client configurations are invalid if user does not specify port in public endpoint

### ISSUE THREAD

**Issue by koonweee** [vx3r/wg-gen-web#81]
To reproduce:
1. Enter Wireguard server port under "Listen port" under "Server's interface configuration"
2. Enter Wireguard server IP under "Public endpoint" under "Client's global configuration" **without port**
3. Create a new client profile
4. Try adding client profile via configuration file or QR code
5.  WireGuard client reports invalid configuration as listen port from server configuration is not appended to public endpoint address

**Comment by vx3r** [comment]
Listen port is the wireguard server's bind port. 
Public endpoint port is for clients to connect to port, in case you have to NAT.
You have to specify both.
