### ISSUE TITLE
!!!!! Very Important Security bug

### ISSUE THREAD

**Issue by PrzemekSkw** [vx3r/wg-gen-web#87]
I have that app on my vpn server and everyone who login with github account can enter my panel and change my wireguard configs.
Regards

**Comment by vx3r** [comment]
this is how oauth2 oidc works, not sure there is a way to limit users

**Comment by malikshi** [comment]
So it's become public server?

**Comment by PrzemekSkw** [comment]
@malikshi Yes, every one who Has github account can login on my panel.

**Comment by malikshi** [comment]
Bad news to Low spec vps and limited bw.

**Comment by PrzemekSkw** [comment]
Yes, I use nginx-proxy, but I don't think it's true that @vx3r says: 

> this is how oauth2 oidc works, not sure there is a way to limit users
There has to be way to secure that. That will be useless.
regards.

**Comment by vx3r** [comment]
i suggest using nginx basic auth or a oauth server you control (self hosted gitlab for example)
