### ISSUE TITLE
add MTU field

### ISSUE THREAD

**Issue by alonbg** [vx3r/wg-gen-web#9]
Thank you

**Comment by alonbg** [comment]
For the client. MTU is a supported field by WireGuard's clients  implementations
```
[Interface]
Address = ****/24,****/64
DNS = 10.8.0.1
MTU = 1280
PrivateKey = **********************
[Peer]
AllowedIPs = 0.0.0.0/0,::/0
Endpoint = ****:54321
PersistentKeepalive = 25
PresharedKey = **********************=
PublicKey = **********************=
```

And for the server, the user should config via the pre/post hooks:
```
# ifconfig wg0 mtu 1280

OR

# ip link set dev wg0 mtu 1280
```

**Comment by alonbg** [comment]
Actually, it's supported by [wg-quick](https://github.com/WireGuard/wireguard-tools/blob/6fabf9c2fbd056c8c6d5ee9ffd69685aab6baaeb/src/wg-quick/linux.bash#L17) for all platforms

**Comment by vx3r** [comment]
Done, please test
