### ISSUE TITLE
the port 8080 should be set by "ports" 

### ISSUE THREAD

**Issue by r4ym0n** [vx3r/wg-gen-web#93]
in compose file , the web port is set by expose , which only expose port in the docker network. 
 ```    
expose:
   - "8080/tcp"
 ```
change it into 
```
ports:
   - "8080:8080"
```
batter

**Comment by vx3r** [comment]
dpends if you use a revers proxy or not, how you want to expose the service to outside world. Using ```ports``` and exposing 8080 without ssl is not a best practice
